name: notion_card
description: "Integrate your notion database with Flashcards"
publish_to: 'none'
version: 1.2.1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  flutter:
    sdk: flutter
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # fonts:
  #   - family: MaterialIcons
  #     fonts:
  #       - asset: fonts/MaterialIcons-Regular.ttf

